name:                logichaskell
version:             0.1.0.0
github:              "githubuser/logichaskell"
license:             BSD-3-Clause
author:              "Jun Zhang"
maintainer:          "yotroy@foxmail.com"
copyright:           "2024 Jun Zhang"
synopsis:            A Haskell library for Computer Science Logic
category:            Development
tested-with:         GHC==9.4.8 || ==9.6.4


extra-source-files:
- README.md
extra-doc-files:
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rT-Troy/Haskell_for_Logic#readme>

dependencies:
- base >= 4.17.2 && < 4.19
- split >= 0.2.5 && < 0.3
- ghc-prim >= 0.9.1 && < 0.11
- pretty >= 1.1.3 && < 1.2
- hspec >= 2.11.7 && < 2.12
- QuickCheck >= 2.14.3 && < 2.15
- hlint >= 3.6 && < 3.9

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-imports
- -Wmissing-export-lists

library:
  source-dirs: src

executables:
  logichaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logichaskell

tests:
  logichaskell-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:
    - CNFSpec
    - CommonSpec
    - DPLLSpec
    - PropResoSpec
    - TruthTableSpec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    - -Wmissing-export-lists
    dependencies:
    - logichaskell